#PROJECT CONFIGURATION

#PROJECT PATH
PROJECT_DIR="/home/rana/Desktop/linux_network_monitor
TARGET_FILE="$PROJECT_DIR/network_monitor.csv"
OUTPUT_DIR="$PROJECT_DIR/output"

#LOG FILE
LOG_FILE="PROJECT_DIR/network_monitor.log"

#NETWORK MONITORING SETTINGS
PING_COUNT=5
PING_TIMEOUT=3
PORT_TIMEOUT=5

#LOGGING
LOG_LEVEL="INFO"

#DATE FORMAT
DATE FORMAT="+%Y-%m-%d %H:%M:%S"

#DOCKER SETTINGS
DOCKER_OUTPUT="/app/output"

#MONITORING INTERVAL
CHECK_INTERVAL=60
