name: Linux Network Monitor CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display project files
        run: ls -la

      - name: Check Bash syntax
        run: bash -n network_monitor.sh

      - name: Build Docker image
        run: docker build -t linux-network-monitor:ci .

      - name: Run Docker container
        run: docker run --rm linux-network-monitor:ci
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        continue-on-error: true
        run: shellcheck network_monitor.sh